name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.x"
    - name: Install dependencies and configure
      run: |
        python -m pip install --upgrade poetry invoke

    - name: Publish
      env:
        TWINE_USERNAME: EdgyEdgemond
        TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISH_TOKEN }}
      run: |
        uv build
        uvx twine upload dist/*
